### ISSUE TITLE
Option to add multiple values of the same attribute in the SmartNodeSelector

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-core-components#128]
Problem:
When filtering on multiple values of the same attribute, the filter will return nothing sinces it's returning the intersection of the filters. The wanted behavior is to take the union of values of the same attribute, and the intersection between different attributes.

![image](https://user-images.githubusercontent.com/47847084/117440513-6e61de80-af34-11eb-9147-98df99636f06.png)

Suggested Solution:
Possibility to select multiple values of the same attribute without adding them as separate filters.

**Comment by rubenthoms** [comment]
@lindjoha have the enhancements in #178 fixed the issue you experienced?

**Comment by rubenthoms** [comment]
@lindjoha #222 might possibly be the solution to your use case. If that is the case, consider closing this issue.

**Comment by lindjoha** [comment]
I have checked in the demo app and the `SmartNodeSelector` now has the wanted behavior. Very good!
