### ISSUE TITLE
totaly new to the python world and can't install the dependencies

### ISSUE THREAD

**Issue by emadbaqeri** [equinor/webviz-core-components#138]
I would like to contribute to react part of the project I wanted to run the project but I have problem with install python dependencies with this command ``` pip install .[dependencies]```.
It throws the error below, maybe this is really easy thing but as I'm totally new to python I can't figure out how to fix this.

![Screenshot from 2021-06-06 22-45-19](https://user-images.githubusercontent.com/50639499/120941122-e6c8e480-c718-11eb-9c24-37eca6db082c.jpg)

I would greatly appreciate you to help me solve this and run the project becuase I'm really eaget to contribute and learn from you cool guys.

**Comment by anders-kiaer** [comment]
Hi @emadbaqeri and welcome to the Python world. :tada:

I don't have `zsh` readily available myself, but I think you can solve it by adding quotes around `.[dependencies]`.

StackOverflow reference: https://stackoverflow.com/a/30539963

We could perhaps consider changing the command to `pip install '.[dependencies]'` in the `README.md` if that doesn't break it in other shells. :thinking:

**Comment by emadbaqeri** [comment]
Hey I fixed the problem I was facing with adding quotes, and also tested that in `fish` and `bash` there is no need to add quotes and following the documentation is going to work on those terminals.
But now the propblem is that I'm following the setup instructions in Contributing section it fails after ```pip install .[dependecies]``` and throw the error below

![Screenshot from 2021-06-07 08-29-52](https://user-images.githubusercontent.com/50639499/120976774-91b5be80-c76a-11eb-885d-849e054d3fd5.jpg)

do I need to install other python packages for running this project or should need to learn python before stating for contributing to this project?

**Comment by anders-kiaer** [comment]
The `npm` command for `package.json` copying need to be run first (it is used both by `npm` and Python/Dash), and I see that the `README.md` is a bit outdated wrt. the commands that should be executed. I created #139 now. We recently refactored this repository to split Python and React further.

The most up to date commands (while waiting for #139 to be closed) is follow the order of the CI commands:
https://github.com/equinor/webviz-core-components/blob/da950feff49fec071f6d73be7f171c6ecd29b487/.github/workflows/webviz-core-components.yml#L35-L38

**Comment by emadbaqeri** [comment]
@anders-kiaer I tried the commands you have mentioned above the error persist I changed the `pip` with `pip3` and that started to install everything without any errors or issues

**Comment by emadbaqeri** [comment]
@anders-kiaer as newbie to open-source how can I help you and guys in this project as a javascript developer? what is the goal of this project? does components have UI design?

**Comment by anders-kiaer** [comment]
@emadbaqeri This repository is a utility repo for https://github.com/equinor/webviz-config (the use cases for the Webviz project is explained a bit over there), containing basic components that `webviz-config` is using (look for `import webviz_core_components` in the `webviz_config` repository to see where they are being used).

The next main UI component/design we will be doing in this repository is probably to make a more advanced menu (see https://webviz-subsurface-example.azurewebsites.net/ for an example of menu to the left). It currently takes up quite a lot of space, and would be also nice if it could support subpages. But that task is probably a bit involved for a first issue. A good way to start learning open source projects is to search for "good first issues". These are the one we currently have labelled across the Webviz project: https://github.com/orgs/equinor/projects/24?card_filter_query=label%3A%22good+first+issue%22

**Comment by rubenthoms** [comment]
Closed.
