### ISSUE TITLE
`SmartNodeSelector` improvement suggestions

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-core-components#149]
- [x] Possible to search on description as well, not necessarily need to know the node/vector name.
- [X] Change from red color on X for removing a selection to same color as for the large X that removes all selections.
- [x] Export data types and TreeData (for VectorSelector)

**Comment by asnyv** [comment]
- [ ] Optional case-insensitive search (very relevant for `VectorSelector`, as `Eclipse` vectors are generally upper case. See https://github.com/equinor/webviz-subsurface-components/issues/444)
