### ISSUE TITLE
Popup component

### ISSUE THREAD

**Issue by jorgenherje** [equinor/webviz-core-components#163]
Create a popup/dialog component for showing content in Dash-plugins

As of now the Modal component from dash-bootstrap-components library is utilized, but it's not optimal. Hard to configure CSS layout, not possible to drag and is always modal.

**Usage:** Nice feature for e.g. advanced plugin-settings, VectorCalculator-component etc.
___________________________________
Consider functionality:
- Draggable?
- Configurable Modal setting?
- ...
- Any more suggestions?

______________________________________________________
Note:
- Check if existing React-components can be utilized:
   - Material-UI
   - ... Any more suggestions?

 - Improve compared to dbc.Modal

**Comment by rubenthoms** [comment]
Closed by #201.
