### ISSUE TITLE
Adjust margin between `WebvizPluginPlaceholder` components

### ISSUE THREAD

**Issue by rubenthoms** [equinor/webviz-core-components#168]
With the new padding in `WebvizPluginPlaceholder` the spacing between these components does not look nice due to an overlap (see image). Adjust the component's margin to avoid the overlap.

![image](https://user-images.githubusercontent.com/69145689/134864960-1fec62ae-fecf-4f3b-a04a-981938650008.png)

**Comment by anders-kiaer** [comment]
The placement of a plugin in "Expanded mode" also looks a bit off now.
