### ISSUE TITLE
"Card" component

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-core-components#20]
Idea from @HansKallekleiv. See picture below:
![image](https://user-images.githubusercontent.com/31612826/64599718-2df63a00-d3ba-11e9-9bcd-cd9877d2aa60.png)

_Benefits:_
 - Less need of layout code in containers
 - Optionally add the possibility of letting single cards become fullscreen.
 - Others?

**Comment by HansKallekleiv** [comment]
Other benefits:
- An information/description button can be added
- Could be used for guided tour functionality

**Comment by rubenthoms** [comment]
@HansKallekleiv @anders-kiaer can you evaluate if this issue is already covered by WLF (#219) and should be closed or potentially missing features extracted?

**Comment by anders-kiaer** [comment]
I would say this is covered by WLF 👍 🎉
