### ISSUE TITLE
Problems with label for `SelectWithLabel`

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-core-components#221]
I have registered two problems with the label of `SelectWithLabel`:

1. It is not possible to change the label in a callback
2. If you hide the component with `style={"display": "none"}`, then the component is hidden, but the label is still there.

**Comment by jorgenherje** [comment]
@lindjoha I would assume this is an example of same issue reported in https://github.com/equinor/webviz-core-components/issues/193

The component from `dash-core-components` ( `dcc`) is placed within a `html.Div` together with a `html.Label`, but the `**kwargs` are only passed to the `Select` component. Thus all styling will only affect the `Select` and not the `html.Label`.

Similar issues yield for other wrapped `dcc` components

**Comment by lindjoha** [comment]
@jorgenherje Yes it is the same issue. Shall I just close this one?

**Comment by jorgenherje** [comment]
@lindjoha I'll close it and add your comments to my issue
