### ISSUE TITLE
Checkboxes in VectorCalculator not selectable

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-core-components#235]
![image](https://user-images.githubusercontent.com/31612826/184092722-0bc83bd9-1f77-48f3-ba62-5e443062c0a4.png)

**Comment by rubenthoms** [comment]
Related to https://github.com/equinor/webviz-subsurface/issues/1101.

**Comment by rubenthoms** [comment]
I did a thorough investigation and did not find this issue related to WLF but to the `Dialog` component.

**Comment by rubenthoms** [comment]
Closed by #236.

**Comment by jorgenherje** [comment]
https://github.com/equinor/webviz-core-components/commit/adbe93f13ce1c9a73b715f1d89aa94afd2975f9b
