### ISSUE TITLE
Allow for the default screenshot filename to be changed

### ISSUE THREAD

**Issue by DanSava** [equinor/webviz-core-components#63]
**Issue**

Currently, when a user clicks on the take screenshot button the component saves a PNG image with the default name `webviz-screenshot.png`

Expose the screenshot filename as a component property in  `WebvizPluginPlaceholder`

**Comment by asnyv** [comment]
Should in that case also be included in [ `WebvizPluginABC`](https://github.com/equinor/webviz-config/blob/master/webviz_config/_plugin_abc.py) (`webviz-config`).

**Comment by DanSava** [comment]
> Should in that case also be included in [ `WebvizPluginABC`](https://github.com/equinor/webviz-config/blob/master/webviz_config/_plugin_abc.py) (`webviz-config`).

Yes, I think it should be included there as well.

**Comment by anders-kiaer** [comment]
Thanks for the feature + pull request @DanSava 🎉🙂 

I've had something related to this on the mental list as well, changing default standard name of exported screenshots to e.g. `(plugin name)(timestamp).png`. We can of course also fully customize it, if there is a use case for that in plugin projects. Can you write a sentence about the use case to be solved, is it to communicate something static per `webviz` session (like `everest` run `id`), or would e.g. plugin name + timestamp suffice as of now? (I guess the most flexible, and complex, solution would be to allow the screenshot name to depend on the user selections front-end.)

**Comment by DanSava** [comment]
I don't think there is a reason to make it fully customizable. 

Also, I find it is easier to distinguish between `filename.png` and `filename(1).png` then between `filename_2038-01-19 03:14:07` and  `filename_2038-01-19 03:17:42`

If we can just change the filename when extending `WebvizPluginABC` in `webviz-config` that is more than enough in my opinion.
