### ISSUE TITLE
Allow raw plot data to be downloaded directly to CSV

### ISSUE THREAD

**Issue by DanSava** [equinor/webviz-core-components#70]
Users of Everviz (which is developed on top of Webviz) have expressed the desire to have the ability to download raw plot data directly to CSV and not as a zip file.  Would it be possible to have an option between ZIP and raw CSV?

**Comment by anders-kiaer** [comment]
This is definitely possible 👍 We actually started with `.csv`, and moved to `.zip` when there were (sometimes) need of downloading large files and/or multiple separate files.

Giving the option to plugin authors to define `zip`/`csv`/others(?) sounds reasonable.

We might, if possible, want to also look into moving away from using `data-uri:` in the implementation, and instead send the files directly with `flask` (the tricky part here could be that the data to be downloaded generally is not static, but "filtered"/selected by the user, and therefore "created" on demand and depends on the state in the front-end...[mighe be some ideas here](https://community.plotly.com/t/allowing-users-to-download-csv-on-click/5550)). Alternatively, if not prioritized now to move away from `data-uri:`, we could for now document what roughly the file size limit is (when using `data-uri:`) to plugin authors.

**Comment by DanSava** [comment]
> We might, if possible, want to also look into moving away from using data-uri: in the implementation, and instead send the files directly with flask

That is an interesting idea but would it be possible to solve it in a different issue? If that is the case I have an implementation suggestion in https://github.com/equinor/webviz-core-components/pull/71

**Comment by anders-kiaer** [comment]
> That is an interesting idea but would it be possible to solve it in a different issue?

Yes, that could be a separate issue and PR.
